apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogapi-config
  namespace: default

data:
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Username: "guest"
  
  ASPNETCORE_ENVIRONMENT: "Production"

  ASPNETCORE_URLS: "http://+:8080"