apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
  labels:
    app: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      initContainers:
        - name: catalog-migrations
          image: catalogapi-migrations:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: catalogapi-secret
      containers:
        - name: catalogapi
          image: catalogapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalogapi-config
            - secretRef:
                name: catalogapi-secret
          env:
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
