apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
  namespace: default
type: Opaque
stringData:
  # SQL Server (Service criado pelo orquestrador)
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service,1433;Database=CatalogDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
  
  # RabbitMQ
  RabbitMQ__Password: "guest"
  
  # JWT (mesma chave usada pelo UsersAPI)
  Jwt__Key: "TechChallengeFIAP2024SecretKeyWith32CharsMin"