apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "SUBSTITUIR_COM_CONNECTION_STRING"
  
  RabbitMQ__Password: "SUBSTITUIR_COM_SENHA"
  
  Jwt__SecretKey: "SUBSTITUIR_COM_CHAVE_MINIMO_32_CARACTERES"
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: default
type: Opaque
stringData:
  sa-password: "SUBSTITUIR_COM_SENHA"