apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
  namespace: default
type: Opaque
stringData:
  # SQL Server
  ConnectionStrings__DefaultConnection: "SUBSTITUIR_COM_CONNECTION_STRING"
  
  # RabbitMQ
  RabbitMQ__Password: "SUBSTITUIR_COM_SENHA"
  
  # JWT
  Jwt__Key: "SUBSTITUIR_COM_CHAVE_MINIMO_32_CARACTERES"