# apiVersion: v1
# kind: Secret
# metadata:
#   name: catalogapi-secret
# type: Opaque
# stringData:
#   # Connection string do banco do Catalog
#   ConnectionStrings__DefaultConnection: "<SQLSERVER_CONNECTION_STRING_CATALOG>"

#   # JWT
#   Jwt__SecretKey: "<JWT_SECRET_KEY>"

#   # Host do RabbitMQ (infra compartilhada)
#   RabbitMQ__Host: "rabbitmq-service"
