apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "<CATALOG_DB_CONNECTION_STRING>"
  Redis__ConnectionString: "fcg-redis.fcg.svc.cluster.local:6379,password=<REDIS_PASSWORD>,abortConnect=false"
  Jwt__SecretKey: "<JWT_SECRET_KEY>"
